// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAXTvBPgPmVD-0YeiR-FuRjwsHLCugzN0',
    appId: '1:655832580681:web:efd784932c4df1d1e63598',
    messagingSenderId: '655832580681',
    projectId: 'waterlevel-project-3185d',
    authDomain: 'waterlevel-project-3185d.firebaseapp.com',
    databaseURL: 'https://waterlevel-project-3185d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-project-3185d.appspot.com',
    measurementId: 'G-NCFGMXQQGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVD5AikRk_14ReLUmCVxGLTGDKSPGjLc',
    appId: '1:655832580681:android:407edb6ad32b56a1e63598',
    messagingSenderId: '655832580681',
    projectId: 'waterlevel-project-3185d',
    databaseURL: 'https://waterlevel-project-3185d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-project-3185d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSyZaIDdXYq7T0Wmzh9Hpewlt6bnRQDyU',
    appId: '1:655832580681:ios:f8c110f4738e8d6de63598',
    messagingSenderId: '655832580681',
    projectId: 'waterlevel-project-3185d',
    databaseURL: 'https://waterlevel-project-3185d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-project-3185d.appspot.com',
    iosClientId: '655832580681-0318hf4didek5tph0i720skugs9u027i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSyZaIDdXYq7T0Wmzh9Hpewlt6bnRQDyU',
    appId: '1:655832580681:ios:f8c110f4738e8d6de63598',
    messagingSenderId: '655832580681',
    projectId: 'waterlevel-project-3185d',
    databaseURL: 'https://waterlevel-project-3185d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waterlevel-project-3185d.appspot.com',
    iosClientId: '655832580681-0318hf4didek5tph0i720skugs9u027i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );
}
